package edu.eci.arsw.concurrent_ws.handler.impl;

import edu.eci.arsw.concurrent_ws.handler.RequestHandler;
import edu.eci.arsw.concurrent_ws.model.HttpRequest;
import edu.eci.arsw.concurrent_ws.model.HttpResponse;
import org.springframework.stereotype.Component;

/**
 * Handler for simple greeting endpoint
 */
@Component
public class HelloHandler implements RequestHandler {

    @Override
    public boolean canHandle(HttpRequest request) {
        return "GET".equals(request.getMethod()) && "/hello".equals(request.getPath());
    }

    @Override
    public HttpResponse handle(HttpRequest request) {
        HttpResponse response = new HttpResponse();
        
        String message = "Hello! Welcome to the Concurrent Web Server!";

        String html = String.format("""
            <!DOCTYPE html>
            <html>
            <head>
                <title>Hello from Concurrent Server</title>
                <style>
                    body { 
                        font-family: Arial, sans-serif; 
                        margin: 40px; 
                        text-align: center; 
                        background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);
                        color: white;
                        min-height: 100vh;
                        display: flex;
                        flex-direction: column;
                        justify-content: center;
                        align-items: center;
                    }
                    .greeting {
                        font-size: 2em;
                        margin-bottom: 20px;
                        text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                    }
                    .info {
                        background: rgba(255,255,255,0.1);
                        padding: 20px;
                        border-radius: 10px;
                        backdrop-filter: blur(10px);
                    }
                    a {
                        color: #ffeb3b;
                        text-decoration: none;
                        font-weight: bold;
                    }
                    a:hover {
                        text-decoration: underline;
                    }
                </style>
            </head>
            <body>
                <div class="greeting">👋 %s</div>
                <div class="info">
                    <p>This response was generated by thread: <strong>%s</strong></p>
                    <p>Response time: <strong>%d ms</strong></p>
                    <p><a href="/">← Back to Home</a></p>
                </div>
            </body>
            </html>
            """, message, Thread.currentThread().getName(), 
            (System.currentTimeMillis() % 1000));

        response.setHtmlBody(html);
        return response;
    }
}
